### ISSUE TITLE
Spring boot + spring Data + h2 in-memory DB = hibernate error

### ISSUE THREAD

**Issue by BeTheCodeWithYou** [authorjapps/spring-boot-integration-test#5]
I have used E2eJunitRunner from the sample but it's NOT starting spring app when run as JUnit Test
I have built a REST API with spring boot , Spring data and h2 in-memory.

Get the following error when running the app as JUnit Test. Please advise. thanks
I can run test cases by running build with skip tests and run the boot jar.

you could refer to my code here https://gitlab.com/Sidhaye/springboot/tree/SpringBoot-RestAPI-ZeroCode-Integration

[0;39m2018-10-16 22:14:10,406 [32m[main][0;39m [31mWARN[0;39m org.springframework.web.context.support.GenericWebApplicationContext - [34mException encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: **Invocation of init method failed; nested exception is org.hibernate.boot.archive.spi.ArchiveException: Could not build ClassFile**

**Comment by authorjapps** [comment]
@macrocks , @aghorpade , @officiallysameer , Can you please have a look?
@dinesh76in , Can you check the H2 in-memory thing as you have done a ticket related to this?

**Comment by authorjapps** [comment]
Hello Neeraj mate @BeTheCodeWithYou, We cloned from your `gitlabs` repo - ie the `gradle` project.
Then without going into details, we just ran your tests:
- Once as it is (All Passed - Green)
- Next time with `H2DataInitializer.java` commented. (2 Failed - as expected)

All looks happy then?

See the screen shots below -
- All passed-
<img width="1206" alt="all pass" src="https://user-images.githubusercontent.com/12598420/47182617-ca849900-d31d-11e8-998c-e1168388f56b.png">

- Pass report-
<img width="1366" alt="report_passed" src="https://user-images.githubusercontent.com/12598420/47183021-e6d50580-d31e-11e8-8e4f-9103dafbb0e5.png">

- 2 Failed(as expected)
<img width="1355" alt="2 failed" src="https://user-images.githubusercontent.com/12598420/47182627-ceb0b680-d31d-11e8-8f97-f4dbdebda715.png">

- Fail report
<img width="900" alt="report_failed" src="https://user-images.githubusercontent.com/12598420/47183050-f3595e00-d31e-11e8-8166-617ac0fa8569.png">

Probably the H2 might be having an issue with your Java version or OS version. You can try a different version of the H2.
Yes, we did a small change in the `Test Java files`, you might have spotted already, but not sure if you missed that by chance. 
> @RunWith(E2eJunitRunner.class)

**Comment by BeTheCodeWithYou** [comment]
Thanks for your time on checking this.
I got the issue now. Today I ran "gradle clean build" and can see only 2 test case failure due to below, so I had to put below entry to my property file.
spring.datasource.url=jdbc:h2:mem:parkrundb;**DB_CLOSE_ON_EXIT=FALSE**

Thanks guys for such impressive library. I am almost done with writing my blog post on the use of this library. Will be publishing on dzone as well. Thanks a lot again.

com.xp.springboot.integrationtest.TestGetOperations > test_getParkRunnerWithValidAndInvalidParkRunId FAILED
    java.lang.RuntimeException

com.xp.springboot.integrationtest.TestGetOperations > test_getAllParkRunners FAILED
    java.lang.RuntimeException
2018-10-19 19:11:24,989 [Thread-7] INFO org.hibernate.tool.schema.internal.SchemaDropperImpl$DelayedDropActionImpl - HHH000477: Starting delayed drop of schema as part of SessionFactory shut-down'
2018-10-19 19:11:24,991 [Thread-7] WARN org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 90121, SQLState: 90121
2018-10-19 19:11:24,992 [Thread-7] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - **Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]**
2018-10-19 19:11:24,996 [Thread-7] WARN org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 90121, SQLState: 90121
2018-10-19 19:11:24,996 [Thread-7] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
2018-10-19 19:11:24,998 [Thread-7] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2018-10-19 19:11:25,015 [Thread-7] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.

**Comment by authorjapps** [comment]
Thank you for your kind appreciations ! Absolutely fantastic news mate for the article thing- we are eagerly awaiting, please let us know when done 👍  
>Thanks guys for such impressive library. I am almost done with writing my blog post on the use of this library. Will be publishing on dzone as well. Thanks a lot again.

Actually your spring-boot project with H2(`Spring boot + spring Data + h2 in-memory DB`) looks awesome, it's a nice example set for `spring-boot` devs/testers, which will make everyone's life much much easier with `Integration-Testing` in the same production code base without writing much code and streamlining the testing i.e. TDD process. Bugs can be found and fixed much before the app hits a SIT/UAT env.

Also, we will also contact you soon for making you sample project public and `mavenize` it with a POM version too. Then we will list your project in our `README` file as well as tweet to the audiences.

Cool stuff mate ! Happy days!

Also please look the cool reports(all the tabs) when you get time 👍

**Comment by BeTheCodeWithYou** [comment]
Sure. Yes I have looked at reports earlier. Awesome stuff.
just quick one, I accidentally deleted the html and csv reports and now when I am again running gradle build, it's not generating those html report even though I can see log files in reports are getting updated.
I am missing anything?

**Comment by BeTheCodeWithYou** [comment]
Is there any possibility to configure such that only latest test execution json files are generated in the  "target\zerocode-test-reports" folder ? At the moment, this folder keeps all test execution json till date.

**Comment by authorjapps** [comment]
Understood. `target\zerocode-test-reports` is cleared for every `mvn clean install` in the `clean` phase.
Equivalent command in the `gradle` should do the job i.e. it should clear the `target` folder and generate the fresh report which is **latest**. 
Otherwise(without the `clean`) the `extent` report displays the earlier test-run results along with the new one(this could be a feature too as we still can get hold of the earlier results). 
It's a maven and extent thing, nothing to do it `zerocode`.

Just fyi only-
There are only two reports generated for each run-
1. CSV one (handy for quick glance and further graph/2d/3d generation via _MS Excel_)
1. HTML one(which has the search n filter option)

`target` folder looks like below(you might have already seen)
<img width="400" alt="reports" src="https://user-images.githubusercontent.com/12598420/47247952-ca0fff00-d3fe-11e8-809f-6f93747d683d.png">

_`target\zerocode-test-reports` has raw reports, not very friendly to interpret, hence not useful for direct viewing. But one can use these to extend further if there is a need as they are also in Json format 👍 ._

An example report here to play with, in the README >> [Reports Section](https://github.com/authorjapps/zerocode/blob/master/README.md#6)
- [Html sample](http://htmlpreview.github.io/?https://github.com/authorjapps/helpme/blob/master/zerocode-rest-help/src/test/resources/zz_reports/zerocode-interactive.html)
- [CSV sample](https://github.com/authorjapps/helpme/blob/master/zerocode-rest-help/src/test/resources/zz_reports/zerocode_full_report_2016-07-30T11-44-14.512.csv)

In the HTMl report above, just keep on typing some text e.g. "John" or "Fail" which filters n shows only matching results. _(text box shown below)_
![search text box](https://user-images.githubusercontent.com/12598420/47248339-a1d5cf80-d401-11e8-9a14-3c70fcb85ee4.png)

**Comment by BeTheCodeWithYou** [comment]
Yeah.. thanks for detailed explanations. that's helpful.

Please checkout my post at my blog at https://extremeportal.blogspot.com/
let me know your comments, if any. thanks a lot.

**Comment by authorjapps** [comment]
Looks cool and to the point 👍 , covers the best practices one should follow for hassle-free Integration-Testing.
Great job, Thanks for your time for writing such a wonderful article.
We have [tweeted](https://twitter.com/ZercodeEasyTDD/status/1053585595841372160) this already

For simplifying `Kafka` testing(which is _In-Progress_) which is interesting part in the article as a bullet point, we will keep you posted as this is massive piece of work and we are half done.
Please add yourself to [Star n Watch](https://github.com/authorjapps/zerocode/stargazers) list here.

**Comment by authorjapps** [comment]
We are done with this ticket(_closing_) now. Happy days !
Please say `Hello` on the [Gitter](https://gitter.im/zerocode-testing/help-and-usage) chat room(_when you get chance_), otherwise see you on Twitter 👍
